### ISSUE TITLE
Overview of who's logged in, available for website guests as well. 

### ISSUE THREAD

**Issue by AlexHartveld** [RefugeesCodeAT/Attendance#1]
As an organiser I want to see who is logged in or who forgot to log out. 

As a participant I want to see if I logged out correctly. 

As a participant I don't want my full name to be shown, initials should be fine.

Ideally: as a participant I can log myself out with a PIN code or password.

**Comment by darioseidl** [comment]
> Ideally: as a participant I can log myself out with a PIN code or password.

We do an auto logout at midnight, and send a mail to remind the participants instead.
