### ISSUE TITLE
Add Standby mode for Raspberry Pi when a new participant on the way to the system.

### ISSUE THREAD

**Issue by AhmedBHameed** [RefugeesCodeAT/Attendance#10]
@darioseidl 

- It is a suggestion to add privilege mode for adding new NFC number to the system the protocol would be like this:

Admin will activate "Standby" mode from the admin panel. back-end will only save any flag that a new user is on the way to be added to the system. Then when new NFC number entered to the system, Raspberry Pi must ask if this flag is on and then send the new NFC number if the flag is off then ignore the new number.

This is a good security if the any one want to play with the system

**Comment by darioseidl** [comment]
Now, when a new NFC card is scanned, the new user is disabled by default. The Admin has to enter their name and then enable them.
