### ISSUE TITLE
Monthly overview

### ISSUE THREAD

**Issue by AlexHartveld** [RefugeesCodeAT/Attendance#6]
Hey Ahmed, 
I love the new lay-out. 
We need to export attendance lists to check presence so this would be the next functionality. 
Is it possible to create a site where the rows are the participants, and the columns are for each 7 weekdays + a week total. 4 times, so you see the whole month. so "Mo" "Tu" "We" "Th" "Fr" "Sa" "Su" "TOT" "Mo". In the top row you can write the date of above each monday. 
In every cell it should say the total hours present (with two digits) e.g. "5,7h" or "6,8h" or (11h)

**Comment by AhmedBHameed** [comment]
@AlexHartveld 
Okay now check the link again you will find a good update.

**Comment by AlexHartveld** [comment]
Looks wonderful! @AhmedBHameed could we have the weekly sum in Bold so it's easier to distinguish it? Or maybe even the whole column with a different background. Whatever looks better or is easer. thx!

**Comment by AhmedBHameed** [comment]
Hey @AlexHartveld 
This is my new enhancement version which still not uploaded to the git cloud. contact Dario to upload the new version.
Your request is done by downloading PDF with week column of different color so it will be very clear for eyes to follow.

**Comment by darioseidl** [comment]
Cool! I deployed your new version now.

**Comment by AhmedBHameed** [comment]
Nice. I will close this issue.
Thanks @darioseidl
If any thing wrong feel free to re-open it.
