### ISSUE TITLE
Logo is not display correctly

### ISSUE THREAD

**Issue by AhmedBHameed** [RefugeesCodeAT/Attendance#7]
- Please make a new logo which is suitable with the size of width: 150px and height: 45px

**Comment by AlexHartveld** [comment]
@AhmedBHameed I've uploaded it as logo2.png

**Comment by AhmedBHameed** [comment]
@AlexHartveld If you have the logo please send it to me to work on it.
I will close this issue as soon you send me the new logo.

**Comment by AlexHartveld** [comment]
It is pushed to the src folder

Sent mobilly
