### ISSUE TITLE
Disable a user

### ISSUE THREAD

**Issue by AlexHartveld** [RefugeesCodeAT/Attendance#8]
Someone started experimenting with their mobile NFC capacities and created 6 new users. Would be nice if I could delete them.

**Comment by AhmedBHameed** [comment]
@darioseidl 
What do you think to meet for this issue. Long time no seen ^-*

**Comment by darioseidl** [comment]
Yes, that would be nice. How about sometime next week?

**Comment by AhmedBHameed** [comment]
Nice. Is Wednesday okay ?
